export const ERROR = "ERROR";

// Auth constants
export const USER_LOADING = "USER_LOADING";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

// Invoice constants
export const ADD_ITEM_CONTAINER_DATA = "ADD_ITEM_CONTAINER_DATA";
export const UPDATE_INVOICE_FORM_DATA = "UPDATE_INVOICE_FORM_DATA";
export const SUBMIT_INVOICE_FORM_DATA = "SUBMIT_INVOICE_FORM_DATA";
export const FETCH_INVOICE_DATA = "FETCH_INVOICE_DATA"; // Changed from FETCH_FIREBASE_INVOICE_DATA
export const DELETE_INVOICE = "DELETE_INVOICE";
export const RESET_INVOICE_FORM = "RESET_INVOICE_FORM";
